stages:
  - build
  - test

services:
  - mysql:5.7

variables:
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_DATABASE: my_cic_test
  MYSQL_ROOT_HOST: mysql
  MYSQL_USER: user
  MYSQL_PASSWORD: secret

  DB_DATABASE: my_cic_test
  DB_HOST: mysql
  DB_USERNAME: root
  DB_PASSWORD: secret

composer:
  image: registry-backend.cic.kz/centras/php-fpm:7.2
  stage: build
  tags:
    - mycic
  script:
    - wget https://getcomposer.org/composer.phar -O ./composer.phar
    - php composer.phar update 
    - cp .env.testing .env
    - php artisan key:generate
  artifacts:
    expire_in: 30 days
    paths:
      - vendor/
      - node_modules/
      - .env
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
      - node_modules/

build:
  image: node:latest
  stage: build
  tags:
    - mycic
  script:
    - npm i
    - npm run dev

phpunit:
  image: registry-backend.cic.kz/centras/php-fpm:7.2
  stage: test
  tags:
    - mycic
  dependencies:
    - composer
  script:
    - cp .env.testing .env && php artisan migrate -v
    - cp .env.testing .env && phpunit --coverage-text --colors=never

####
