services:
  - mysql:5.7

variables:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: my_cic_test
  MYSQL_ROOT_HOST: mysql
  MYSQL_USER: user
  MYSQL_PASSWORD: secret

  DB_DATABASE: my_cic_test
  DB_HOST: mysql
  DB_USERNAME: root
  DB_PASSWORD: secret

before_script:
  - apt-get update
  - apt-get install -y libxml2-dev wget zlib1g-dev libwebp-dev libjpeg62-turbo-dev libpng-dev libxpm-dev libfreetype6-dev
  - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
  - docker-php-ext-install xml soap zip gd
  - docker-php-ext-install mysql && docker-php-ext-enable mysql
  - apt-get clean
  - php -v
  - php -i

composer:
  image: php:7.2
  stage: build
  script:
    - wget https://getcomposer.org/composer.phar -O ./composer.phar
    - php composer.phar update 
    - cp .env.testing .env
    - php artisan key:generate
  artifacts:
    expire_in: 30 days
    paths:
      - vendor/
      - node_modules/
      - .env
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
      - node_modules/

build:
  image: node:latest
  stage: build
  script:
    - npm i
    - npm run dev

phpunit:
  image: php:7.2
  stage: test
  dependencies:
    - composer
  script:
    - php artisan migrate -v
    - phpunit --coverage-text --colors=never

