image: lorisleiva/laravel-docker:latest

services:
  - mysql:5.7

variables:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: my_cic_test
  MYSQL_ROOT_HOST: mysql
  MYSQL_USER: user
  MYSQL_PASSWORD: secret

  DB_DATABASE: my_cic_test
  DB_HOST: mysql
  DB_USERNAME: root
  DB_PASSWORD: secret

composer:
  stage: build
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.testing .env
    - php artisan key:generate
  artifacts:
    expire_in: 30 days
    paths:
      - vendor/
      - .env
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
      - node_modules/

build
  stage: build
  script:
    - npm i
	- npm run build

phpunit:
  stage: test
  dependencies:
    - composer
  script:
    - php artisan migrate -v
    - phpunit --coverage-text --colors=never
...
