version: "3"

# Live Reloading: https://betterprogramming.pub/live-reloading-with-docker-compose-for-efficient-development-356d50e91e39
# Docker-compose: идеальное рабочее окружение https://habr.com/ru/post/346086/

networks:
  mycic_network:
    driver: bridge

services:
  mycic_redis:
    image: redis:latest
    container_name: mycic_redis
    hostname: redis.docker

    ports:
      - "6379:6379"

    networks:
      - mycic_network

  mycic_php:
    image: registry-backend.cic.kz/centras-php7.3-fpm:develop
    container_name: mycic_php
    hostname: php.docker

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - .:/app
      - ./.docker/php/supervisord:/etc/supervisor
      - ./.docker/logs/supervisord:/logs/supervisor

    depends_on:
      - mycic_redis

    links:
      - mycic_db

    networks:
      - mycic_network

  # mycic_frontend_builder:
  #   image: node:latest
  #   container_name: mycic_frontend_builder
  #   build:
  #     context: ./.docker/frontend
  #
  #   volumes:
  #     - .:/app
  #     - ./node_modules

  mycic_nginx:
    image: nginx:latest
    container_name: mycic_nginx
    hostname: nginx.docker
    volumes:
     - .docker/nginx:/etc/nginx/conf.d
     - .docker/logs/nginx:/logs
     - .:/app

    ports:
     - "8081:80"
    depends_on:
     - mycic_php
     - mycic_db

    networks:
      - mycic_network

  mycic_db:
    image: registry-backend.cic.kz/mysql5.7:develop
    container_name: mycic_db
    hostname: db.docker

    restart: unless-stopped
    tty: true

    environment:
      MYSQL_ROOT_PASSWORD: 12345678

    ports:
      - "33060:3306"

    networks:
      - mycic_network

# TODO Add Node image that builds frontend in watch-mode
# +TODO Add MySQL
# TODO Make MySQL available
# TODO Add Supervisor or another
# TODO Add ...
