version: "3"

# Live Reloading: https://betterprogramming.pub/live-reloading-with-docker-compose-for-efficient-development-356d50e91e39
# Docker-compose: идеальное рабочее окружение https://habr.com/ru/post/346086/

networks:
  app-tier:
    driver: bridge

services:
  mycic_redis:
    container_name: mycic_redis
    image: redis

    hostname: redis.docker

  mycic_php:
    container_name: mycic_php

    image: bitnami/php-fpm:latest

    ports:
      - "8000:9000"

    volumes:
      - .docker/php:/app

    hostname: php.docker
    depends_on:
      - mycic_redis

    networks:
      - app-tier

  mycic_nginx:
    container_name: mycic_nginx
    image: nginx:latest
    volumes:
     - ./.docker/nginx:/etc/nginx/conf.d
     - ./.docker/logs/nginx:/logs
    ports:
     - "8080:80"
    hostname: nginx.docker
    depends_on:
     - mycic_php

    networks:
      - app-tier
