version: "3"

# Live Reloading: https://betterprogramming.pub/live-reloading-with-docker-compose-for-efficient-development-356d50e91e39
# Docker-compose: идеальное рабочее окружение https://habr.com/ru/post/346086/

networks:
  app-tier:
    driver: bridge

services:
  mycic_redis:
    container_name: mycic_redis
    image: redis

    hostname: redis.docker

  mycic_php:
    container_name: mycic_php

    image: "php:7-fpm"

    ports:
      - "9000:9000"

    volumes:
      - .:/app

    hostname: php.docker
    depends_on:
      - mycic_redis

    networks:
      - app-tier

  mycic_frontend_builder:
    container_name: mycic_frontend_builder
    image: node:latest
    build:
      context: .
      dockerfile: ./.docker/frontend/Dockerfile

    command: ["ls", "app"]

    volumes:
      - .:/app
      - ./node_modules

  mycic_nginx:
    container_name: mycic_nginx
    image: nginx:latest
    volumes:
     - .docker/nginx:/etc/nginx/conf.d
     - .docker/logs/nginx:/logs
     - .:/app

    ports:
     - "8081:80"
    hostname: nginx.docker
    depends_on:
     - mycic_php
     - mycic_frontend_builder

    networks:
      - app-tier

# TODO Add Node image that builds frontend in watch-mode
# TODO Add MySQL
# TODO Add Supervisor or another
# TODO Add ...
