<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use App\Dictionary;

/**
 * Class Kurators
 * @property integer $user_isn ISN таргета
 * @property integer $permission_id ID уровня доступа
 * @package App
 */
class Kurators extends Model
{
    use SoftDeletes;

    public $user;
    const ACTION_NEW = 'new';
    const ACTION_UPDATE = 'update';
    const ACTION_DELETE = 'delete';

    const ROLE_KURATORS = 8;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }

    public function hasKurator($user){
        $data = self::where('user_isn', $user->ISN)->get();
        dd($data);
    }

    public function getKuratorLabel(){
        return Dictionary::findOrFail($this->permission_id)->name;
    }

    public function save(array $options = [])
    {
        $this->changer = Auth::user()->ISN;
        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function checkUser($roles){
        array_push($roles, Kurators::ROLE_KURATORS);
        $data = Permissions::whereIn('permission_id', $roles)
            ->where('user_isn',Auth::user()->ISN)
            ->first();
        return $data === null ? false : true;
    }
}
