<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class RatingPermission extends Model
{
    use SoftDeletes;

    public $user;
    const ACTION_NEW = 'new';
    const ACTION_UPDATE = 'update';
    const ACTION_DELETE = 'delete';

    const ROLE_KURATORS = 9;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }

    public function hasKurator($user){
        $data = self::where('user_isn', $user->ISN)->get();
    }

    public function getKuratorLabel(){
        return Dictionary::findOrFail($this->permission_id)->name;
    }

    public function save(array $options = [])
    {
        $this->changer = Auth::user()->ISN;
        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function checkUser($roles){
        array_push($roles, RatingPermission::ROLE_KURATORS);
        $data = Permissions::whereIn('permission_id', $roles)
            ->where('user_isn',Auth::user()->ISN)
            ->first();
        return $data === null ? false : true;
    }

    public function getActiveUsers() {
        $data = RatingPermission::where('active', 1)->pluck('user_isn')->toArray();

        if($data !== null) {
            return $data;
        }
        else
            return [];
    }
}
