### Authorization
POST http://{{host}}/login
Content-Type: application/json

{
    "username": "Developer",
    "password": "password"
}


### Get user data
POST http://{{host}}/getUsersData

> {%
     client.test("Must return the user data", function() {
       client.assert(response.body.success === true, "Success value is not true");
       client.assert(response.body.response.Name === "Developer", "Name is not Developer");
     });
 %}

### Get posts
POST http://{{host}}/news/getPosts

> {%
    client.test('Must return the array of posts', function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(typeof response.body === 'object', "Type of response body is not an object");
        client.assert(typeof response.body.length === 'number', "Response status is not an array");
    });
 %}

### Get likes
POST http://{{host}}/news/getLikes
Accept: application/json

{
  "postId": 1
}


### Get user data
