<?php

namespace Tests\Unit;

use App\Http\Resources\QuizResource;
use App\Library\Services\Quiz\QuizSaveService;
use App\Quiz;
use App\QuizAnswers;
use App\QuizQuestion;
use App\Repository\Eloquent\QuizRepository;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use PHPUnit\Framework\TestCase;

class QuizSaveServiceTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    //Service
    public function testQuizParametersSave()
    {
        $request = ["quiz" => [
            "name" => "Алгебр",
            "passing_score" => "80",
            "time" => "02:00:01",
            "description" => "Очень сложный",
        ]];
        $quizzes = [
            [
                [
                    "1)  2+2 = ?",
                    "A)5",
                    "B)12",
                    "C)85",
                    "D)4",
                    3
                ],
                [
                    "2) Где?",
                    "A)Алматы",
                    "B)Караганде",
                    "C)Нурсултане",
                    "D)Шым",
                    4
                ]
            ]
        ];

        $result = app(QuizSaveService::class)->quizParametersSave($request, $quizzes);
        $bool = $result > 0 ;
        $this->assertTrue($bool);
        $this->checkQuizParams($result, $request);
        $this->checkQuestions($result, $quizzes);
        $delete = $this->deleteTest($result);
        $this->assertTrue($delete);

    }

    private function checkQuizParams($id, $request)
    {
        $model = app(QuizRepository::class)->find($id);
        $this->assertEquals($model->name, $request['quiz']['name']);
        $this->assertEquals($model->passing_score, $request['quiz']['passing_score']);
        $this->assertEquals($model->time, $request['quiz']['time']);
        $this->assertEquals($model->description, $request['quiz']['description']);
    }

    private function checkQuestions($id, $quizzes)
    {

        $modalQuestion = QuizQuestion::where('quiz_id', $id)->get();

        foreach ($modalQuestion as $k => $question) {
            $this->assertEquals($quizzes[0][$k][0], $question['question']);
        }

    }

    private function deleteTest($id)
    {
        return Quiz::find($id)->delete();
    }
}
